environment:
  nodejs_version: "6"
services:
  - "mongodb"
install:
  - ps: Install-Product node 6
  - "npm -g install npm@latest"
  - "set PATH=%APPDATA%\\npm;%PATH%"
  - "npm install --no-optional"
build: off
before_test:
  - "node --version"
  - "npm --version"
  - "npm info dredd version"
test_script:
  - "npm test"
